# Site settings
title: Near Improv
email: richard.m.law@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Musings on spatial data, transportation, and spatial transportation data in
  New Zealand and beyond
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: "/:title"
url: "http://nearimprov.com" # the base hostname & protocol for your site
twitter_username: alphabeta_soup
github_username:  alpha-beta-soup

# Build settings
#markdown: kramdown
markdown: redcarpet

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
